# =============================================================================
# [Console YAML Sample] DataVolume
# OpenShift Console > + 버튼 (Import YAML) 에서 붙여넣기 후 사용
# =============================================================================
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: fedora-dv
  namespace: poc-storage-dv
spec:
  sourceRef:
    kind: DataSource
    name: fedora
    namespace: openshift-virtualization-os-images
  storage:
    resources:
      requests:
        storage: 20Gi
    accessModes:
      - ReadWriteOnce
