apiVersion: cdi.kubevirt.io/v1beta1
kind: DataSource
meta
  name: poc
  namespace: openshift-virtualization-os-images
spec:
  source:
    pvc:
      name: poc-golden
      namespace: openshift-virtualization-os-images

