apiVersion: template.openshift.io/v1
kind: Template
meta
  name: poc
  namespace: openshift
  labels:
    app.kubernetes.io/part-of: hyperconverged-cluster
    flavor.template.kubevirt.io: small
    template.kubevirt.io/version: v0.31.1
    template.kubevirt.io/type: vm
    vm.kubevirt.io/template: rhel9-server-small
    app.kubernetes.io/component: templating
    app.kubernetes.io/managed-by: ssp-operator
    os.template.kubevirt.io/rhel9.0: "true"
    os.template.kubevirt.io/rhel9.1: "true"
    os.template.kubevirt.io/rhel9.2: "true"
    os.template.kubevirt.io/rhel9.3: "true"
    os.template.kubevirt.io/rhel9.4: "true"
    os.template.kubevirt.io/rhel9.5: "true"
    vm.kubevirt.io/template.namespace: openshift
    app.kubernetes.io/name: custom-templates
    workload.template.kubevirt.io: server
    annotations:
      openshift.io/display-name: POC VM
      description: Template for Red Hat Enterprise Linux 9 VM or newer.
      tags: hidden,kubevirt,virtualmachine,linux,rhel
      iconClass: icon-rhel
      template.kubevirt.io/version: v1alpha1
  defaults:
    template.kubevirt.io/disk.rootdisk: template.openshift.io/bindable: false
    openshift.kubevirt.io/pronounceable-suffix-for-name-expression: "true"
  name.os.template.kubevirt.io/rhel9.0: Red Hat Enterprise Linux 9.0 or higher
  name.os.template.kubevirt.io/rhel9.1: Red Hat Enterprise Linux 9.0 or higher
  name.os.template.kubevirt.io/rhel9.2: Red Hat Enterprise Linux 9.0 or higher
  name.os.template.kubevirt.io/rhel9.3: Red Hat Enterprise Linux 9.0 or higher
  name.os.template.kubevirt.io/rhel9.4: Red Hat Enterprise Linux 9.0 or higher
  name.os.template.kubevirt.io/rhel9.5: Red Hat Enterprise Linux 9.0 or higher
objects:
  - apiVersion: kubevirt.io/v1
    kind: VirtualMachine
    meta
      annotations:
        vm.kubevirt.io/validations: |
          - path: jsonpath='{.spec.domain.memory.guest}'
            rule: integer
            message: This VM requires more memory.
            min: 1610612736
      labels:
        app: ${NAME}
        kubevirt.io/domain: ${NAME}
        kubevirt.io/size: small
      name: ${NAME}
    spec:
      dataVolumeTemplates:
        - apiVersion: cdi.kubevirt.io/v1beta1
          kind: DataVolume
          meta
            name: ${NAME}
          spec:
            sourceRef:
              kind: DataSource
              name: ${DATASOURCENAME}
              namespace: ${DATASOURCENAMESPACE}
            storage:
              resources:
                requests:
                  storage: 30Gi
      running: false
      template:
        meta
          annotations:
            vm.kubevirt.io/flavor: small
            vm.kubevirt.io/os: rhel9
            vm.kubevirt.io/workload: server
          labels:
            kubevirt.io/domain: ${NAME}
            kubevirt.io/size: small
        spec:
          architecture: amd64
          domain:
            cpu:
              cores: 1
              sockets: 1
              threads: 1
            devices:
              disks:
                - disk:
                    bus: virtio
                  name: rootdisk
                - disk:
                    bus: virtio
                  name: cloudinitdisk
              interfaces:
                - masquerade:
                  model: virtio
                name: default
              rng: {}
              features:
                smm:
                  enabled: true
              firmware:
                bootloader: efi
            memory:
              guest: 2Gi
            networks:
              - name: default
                pod: {}
            terminationGracePeriodSeconds: 180
            volumes:
              - dataVolume:
                  name: ${NAME}
                name: rootdisk
              - cloudInitNoCloud:
                  userData: |
                    #cloud-config
                    user: cloud-user
                    password: ${CLOUDUSERPASSWORD}
                    chpasswd: { expire: False }
                name: cloudinitdisk
          parameters:
            - name: NAME
              description: VM name
              generate: "poc-${a-z0-9|16}"
            - name: DATASOURCENAME
              description: Name of the DataSource to clone
              value: poc
            - name: DATASOURCENAMESPACE
              description: Namespace of the DataSource
              value: openshift-virtualization-os-images
            - name: CLOUDUSERPASSWORD
              description: Randomized password for the cloud-init user cloud-user
              generate: "expression-from('a-z0-9', 4) + '-' + expression-from('a-z0-9', 4) + '-' + expression-from('a-z0-9', 4)"

